name: Deploy backend in GCP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 

      - name: Install dependencies
        run: npm install
          
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.5.0'

      - name: Terraform Init
        working-directory: terraform/
        run: terraform init

      - name: Terraform Plan
        run: |
          terraform -chdir=terraform plan \
            -var "project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var "region=${{ secrets.GCP_REGION }}" \
            -var "cloud_sql_instance_connection_name=${{ secrets.DB_INSTANCE_CONNECTION_NAM }}" \
            -var "cloud_run_service_account=${{ secrets.CLOUD_RUN_SA }}"
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_REGION: ${{ secrets.GCP_REGION }}
          DB_INSTANCE_CONNECTION_NAM: ${{ secrets.DB_INSTANCE_CONNECTION_NAM }}
          CLOUD_RUN_SA: ${{ secrets.CLOUD_RUN_SA }}

      - name: Terraform Apply
        run: |
          terraform -chdir=terraform apply -auto-approve \
            -var "project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var "region=${{ secrets.GCP_REGION }}" \
            -var "cloud_sql_instance_connection_name=${{ secrets.DB_INSTANCE_CONNECTION_NAM }}" \
            -var "cloud_run_service_account=${{ secrets.CLOUD_RUN_SA }}"
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_REGION: ${{ secrets.GCP_REGION }}
          DB_INSTANCE_CONNECTION_NAM: ${{ secrets.DB_INSTANCE_CONNECTION_NAM }}
          CLOUD_RUN_SA: ${{ secrets.CLOUD_RUN_SA }}
          
      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: 'gcr.io'

      - name: Build and Push Docker Image
        run: |
          docker build --build-arg DB_HOST=${{ secrets.DB_HOST }} \
            --build-arg DB_PORT=${{ secrets.DB_PORT }} \
            --build-arg DB_DATABASE=${{ secrets.DB_DATABASE }} \
            --build-arg DB_USERNAME=${{ secrets.DB_USERNAME }} \
            --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --build-arg DB_TYPE=${{ secrets.DB_TYPE }} \
            --build-arg PORT=${{ secrets.PORT }} \
            --build-arg API_MOVIE_KEY=${{ secrets.API_MOVIE_KEY }} \
            --build-arg API_MOVIE_URL=${{ secrets.API_MOVIE_URL }} \
            --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            --build-arg OPENAI_ORGANIZATON=${{ secrets.OPENAI_ORGANIZATON }} \
            --build-arg OPENAI_PROJECT=${{ secrets.OPENAI_PROJECT }} \
            --build-arg REDIS_URL=${{ secrets.REDIS_URL }} \
            --build-arg REDIS_KEY=${{ secrets.REDIS_KEY }} \
            --build-arg REDIS_PORT=${{ secrets.REDIS_PORT }} \
            --build-arg DEFAULT_EXPIRATION_TIME=${{ secrets.DEFAULT_EXPIRATION_TIME }} \
            --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/movie_project_bk:latest .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/movie_project_bk:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: movie-project-bk
          image: gcr.io/${{ secrets.GCP_PROJECT_ID}}/movie_project_bk
          region: ${{ secrets.GCP_REGION }}
          platform: managed
          allow-authenticated: false
          cloud_sql_instances: ${{ secrets.DB_INSTANCE_CONNECTION_NAM }}
          vpc_access_connector: vpc-connector-movies
        
        
